name: Continuous integration

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"

jobs:
  lint_and_test:
    name: Run format check and unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      run: |
        pip install --upgrade setuptools pip 
        pip install -e .
    - name: Check format and lint
      run: |
        black --check --diff .
        pylint app.py
    - name: Start dev env
      run: flask_camp dev_env
    - run: pytest
